import { IChord, Notes, Qualities, Sevenths, Thirteenths, Ninths } from "../src";

export interface IChordTestData {
    name: string;
    chord: IChord;
}

export namespace TestData {
    export const correctPairsWithCanonicalNames: IChordTestData[] = [
        {
            name: "A",
            chord: {
                symbol: {
                    rootNote: Notes.A,
                    quality: undefined,
                    seventh: undefined,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: false,
                    4: true,
                    5: false,
                    6: false,
                    7: true,
                    8: false,
                    9: false,
                    10: false,
                    11: false,
                },
            },
        },
        {
            name: "Bb",
            chord: {
                symbol: {
                    rootNote: Notes.BFlat,
                    quality: undefined,
                    seventh: undefined,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: false,
                    4: true,
                    5: false,
                    6: false,
                    7: true,
                    8: false,
                    9: false,
                    10: false,
                    11: false,
                },
            },
        },
        {
            name: "C#",
            chord: {
                symbol: {
                    rootNote: Notes.CSharp,
                    quality: undefined,
                    seventh: undefined,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: false,
                    4: true,
                    5: false,
                    6: false,
                    7: true,
                    8: false,
                    9: false,
                    10: false,
                    11: false,
                },
            },
        },
        {
            name: "Am",
            chord: {
                symbol: {
                    rootNote: Notes.A,
                    quality: Qualities.Minor,
                    seventh: undefined,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: true,
                    4: false,
                    5: false,
                    6: false,
                    7: true,
                    8: false,
                    9: false,
                    10: false,
                    11: false,
                },
            },
        },
        {
            name: "Bbm",
            chord: {
                symbol: {
                    rootNote: Notes.BFlat,
                    quality: Qualities.Minor,
                    seventh: undefined,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: true,
                    4: false,
                    5: false,
                    6: false,
                    7: true,
                    8: false,
                    9: false,
                    10: false,
                    11: false,
                },
            },
        },
        {
            name: "C#m",
            chord: {
                symbol: {
                    rootNote: Notes.CSharp,
                    quality: Qualities.Minor,
                    seventh: undefined,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: true,
                    4: false,
                    5: false,
                    6: false,
                    7: true,
                    8: false,
                    9: false,
                    10: false,
                    11: false,
                },
            },
        },
        {
            name: "Dbm/G#",
            chord: {
                symbol: {
                    rootNote: Notes.DFlat,
                    quality: Qualities.Minor,
                    seventh: undefined,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: Notes.GSharp,
                },
                structure: {
                    1: false,
                    2: false,
                    3: true,
                    4: false,
                    5: false,
                    6: false,
                    7: true,
                    8: false,
                    9: false,
                    10: false,
                    11: false,
                },
            },
        },
        {
            name: "G#maj7",
            chord: {
                symbol: {
                    rootNote: Notes.GSharp,
                    quality: Qualities.Major,
                    seventh: Sevenths.Seventh,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: false,
                    4: true,
                    5: false,
                    6: false,
                    7: true,
                    8: false,
                    9: false,
                    10: false,
                    11: true,
                },
            },
        },
        {
            name: "Bmmaj13/F#",
            chord: {
                symbol: {
                    rootNote: Notes.B,
                    quality: Qualities.MinorMajor,
                    seventh: undefined,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: Thirteenths.Major13,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: Notes.FSharp,
                },
                structure: {
                    1: false,
                    2: true,
                    3: true,
                    4: false,
                    5: true,
                    6: false,
                    7: true,
                    8: false,
                    9: true,
                    10: false,
                    11: true,
                },
            },
        },
        {
            name: "A7b9b13",
            chord: {
                symbol: {
                    rootNote: Notes.A,
                    quality: undefined,
                    seventh: Sevenths.Seventh,
                    ninth: Ninths.Minor9,
                    eleventh: undefined,
                    thirteenth: Thirteenths.Minor13,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: true,
                    2: false,
                    3: false,
                    4: true,
                    5: true,
                    6: false,
                    7: true,
                    8: true,
                    9: false,
                    10: true,
                    11: false,
                },
            },
        },
        {
            name: "C#dim7",
            chord: {
                symbol: {
                    rootNote: Notes.CSharp,
                    quality: Qualities.Diminished,
                    seventh: Sevenths.Seventh,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: true,
                    4: false,
                    5: false,
                    6: true,
                    7: false,
                    8: false,
                    9: true,
                    10: false,
                    11: false,
                },
            },
        },
    ];

    export const correctPairsWithNonCanonicalNames: IChordTestData[] = [
        {
            name: "G#M7",
            chord: {
                symbol: {
                    rootNote: Notes.GSharp,
                    quality: Qualities.Major,
                    seventh: Sevenths.Seventh,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: false,
                    4: true,
                    5: false,
                    6: false,
                    7: true,
                    8: false,
                    9: false,
                    10: false,
                    11: true,
                },
            },
        },
        {
            name: "BmM13/F#",
            chord: {
                symbol: {
                    rootNote: Notes.B,
                    quality: Qualities.MinorMajor,
                    seventh: undefined,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: Thirteenths.Major13,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: Notes.FSharp,
                },
                structure: {
                    1: false,
                    2: true,
                    3: true,
                    4: false,
                    5: true,
                    6: false,
                    7: true,
                    8: false,
                    9: true,
                    10: false,
                    11: true,
                },
            },
        },
        {
            name: "C#07",
            chord: {
                symbol: {
                    rootNote: Notes.CSharp,
                    quality: Qualities.Diminished,
                    seventh: Sevenths.Seventh,
                    ninth: undefined,
                    eleventh: undefined,
                    thirteenth: undefined,
                    addeds: new Set(),
                    suspendeds: new Set(),
                    alteredFifth: undefined,
                    bassNote: undefined,
                },
                structure: {
                    1: false,
                    2: false,
                    3: true,
                    4: false,
                    5: false,
                    6: true,
                    7: false,
                    8: false,
                    9: true,
                    10: false,
                    11: false,
                },
            },
        },
    ];

    export const incorrectNames: string[] = ["", "T", "Ah", "Cb", "E#", "Cdim#5", "Caugb5", "E57", "Em5", "E5b5"];
}
